### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cben** [FirebaseExtended/firepad-demo#1]
Being shamelessly lazy, I'd like to steal some of the pad id from URL & new random pad logic.
Could you add a LICENSE file to this repo?

**Comment by cben** [comment]
Better yet, directly include/link to the relevant snippets in Firepad docs.
(This repo is a bit hard to find as the demo page's "Fork on GitHub" links to the main firepad repo.)

I now see firepad/examples/example-helper.js & randomString() in firepad/test/lib/helpers.js are useful.

**Comment by mikelehen** [comment]
I added the LICENSE file.  That should have been there.  Thanks!

I'll think about finding a place to document the pad id / random pad logic.  It's not really Firepad-specific, but I do see how it's a convenient piece of code...

**Comment by cben** [comment]
Thanks.

Researching this more, I learnt that Math.random() is quite weak - perhaps fully predictable from time - on many browsers: http://stackoverflow.com/a/18507748/239657.
If you document it, it's worth warning people of that, and recommending window.crypto.getRandomValues() where available:
https://developer.mozilla.org/en-US/docs/Web/API/window.crypto.getRandomValues 
(There are also libraries - Clipperz, SJCL - that can collect entropy from mouse events etc.  Ugh...)

**Comment by mikelehen** [comment]
Ahh, very good point.  Thanks for the follow-up. :-)
